"""Create DB

Revision ID: 4415ac33b228
Revises: 
Create Date: 2024-02-10 15:51:03.031761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4415ac33b228'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Город', sa.String(), nullable=False),
    sa.Column('Страна', sa.String(), nullable=False),
    sa.Column('Широта', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('Долгота', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Город')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    # ### end Alembic commands ###
